version: "3.7"
services:
  divel-web:
    build:
      args:
        user: divel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: divel-web
    container_name: divel-web
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - divel-app

  divel-db:
    image: mysql:8.0
    container_name: divel-db
    restart: unless-stopped
    ports:
        - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
    - 3306:3306  
    volumes:
      - divel-db-volume:/var/lib/mysql
    networks:
      - divel-app

  divel-nginx:
    image: nginx:alpine
    container_name: divel-nginx
    restart: unless-stopped
    ports:
      - 9000:80
      - 3000:3000
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/dev:/etc/nginx/conf.d/
    networks:
      - divel-app

networks:
  divel-app:
    driver: bridge
volumes:
  divel-db-volume:
